[package]
name = "asset_tree"
version = "0.1.0"
edition = "2021"

[features]
no_log = []
no_std = ["dep:hashbrown"]

default = []

[[example]]
name = "full"
required-features = ["default"]

[dependencies]
paste = "1.0.15"

hashbrown = { optional = true, version = "0.15" }
